[all:vars]
ansible_user=admin-sburns
k8s_version=1.30
vip=192.168.200.50
vip_port=16443

[control_planes]
nobu-ctrl01 ansible_host=192.168.200.51 priority=100 state=MASTER
nobu-ctrl02 ansible_host=192.168.200.52 priority=90  state=BACKUP
nobu-ctrl03 ansible_host=192.168.200.53 priority=80  state=BACKUP

[workers]
nobu-wrk01 ansible_host=192.168.200.54
nobu-wrk02 ansible_host=192.168.200.55
nobu-wrk03 ansible_host=192.168.200.56
